#!/usr/bin/env python3
"""Generate the committed DXBC table used by the DX12 renderer.

Only three shader sets exist: 1x-4x, 5x-8x and 9x-16x. Values that vary
inside those buckets are supplied through MetaUniform at runtime.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import os
import struct
import subprocess
import sys
import tempfile


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
AUDIT_PATH = os.path.join(REPO_ROOT, "tools", "ci", "audits", "check-dx12-shaders.py")
OUTPUT_PATH = os.path.join(REPO_ROOT, "src", "GPU3D_DX12_ShaderBlobs.inc")
BUCKET_SCALES = (1, 5, 9)


def load_audit_module():
    spec = importlib.util.spec_from_file_location("melonprime_dx12_shader_audit", AUDIT_PATH)
    if spec is None or spec.loader is None:
        raise SystemExit(f"could not load {AUDIT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def source_hash() -> str:
    digest = hashlib.sha256()
    paths = (AUDIT_PATH, __file__, os.path.join(REPO_ROOT, "src", "GPU3D_DX12_shaders.h"))
    for path in sorted(paths):
        relative = os.path.relpath(path, REPO_ROOT).replace(os.sep, "/")
        with open(path, "rb") as handle:
            content = handle.read().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(content)
        digest.update(b"\0")
    digest.update(repr(BUCKET_SCALES).encode("ascii"))
    return digest.hexdigest()


def compile_all(audit, fxc: str) -> tuple[list[bytes], list[tuple[int, int]]]:
    shaders = audit.parse_shaders(audit.SHADER_HEADER)
    variants = audit.variants()
    blobs: list[bytes] = []
    ranges: list[tuple[int, int]] = []
    offset_words = 0

    with tempfile.TemporaryDirectory(prefix="melonprime-dx12-generate-") as temp_dir:
        source_path = os.path.join(temp_dir, "shader.hlsl")
        output_path = os.path.join(temp_dir, "shader.dxbc")
        for scale in BUCKET_SCALES:
            geometry = audit.geometry(scale)
            for name, body_key, defines in variants:
                source = audit.build_source(shaders, geometry, body_key, defines)
                with open(source_path, "w", encoding="utf-8") as handle:
                    handle.write(source)
                result = subprocess.run(
                    [fxc, "/nologo", "/T", "cs_5_1", "/E", "main", "/O3",
                     "/Ges", "/Fo", output_path, source_path],
                    capture_output=True,
                    text=True,
                )
                diagnostics = "\n".join(
                    part.strip() for part in (result.stdout, result.stderr) if part.strip())
                if result.returncode != 0 or "warning " in diagnostics.lower():
                    print(f"FAIL: bucket-scale={scale} shader={name}\n{diagnostics}", file=sys.stderr)
                    raise SystemExit(1)
                with open(output_path, "rb") as handle:
                    blob = handle.read()
                if len(blob) % 4 != 0:
                    raise SystemExit(f"{name}: DXBC byte length is not word aligned")
                blobs.append(blob)
                ranges.append((offset_words, len(blob)))
                offset_words += len(blob) // 4

    return blobs, ranges


def render(blobs: list[bytes], ranges: list[tuple[int, int]], digest: str, variant_count: int) -> str:
    words: list[int] = []
    for blob in blobs:
        words.extend(struct.unpack(f"<{len(blob) // 4}I", blob))

    lines = [
        "// Generated by tools/dx12/compile-shaders.py. Do not edit.",
        f"// Source SHA256: {digest}",
        "namespace melonDS::DX12ShaderBlobs",
        "{",
        "struct Blob { const void* Data; std::size_t Size; };",
        "struct Range { u32 WordOffset; u32 ByteSize; };",
        f"inline constexpr u32 BucketCount = {len(BUCKET_SCALES)}u;",
        f"inline constexpr u32 VariantCount = {variant_count}u;",
        "alignas(4) static constexpr u32 Words[] = {",
    ]
    for base in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08X}u" for word in words[base:base + 8]) + ",")
    lines += ["};", "static constexpr Range Ranges[BucketCount][VariantCount] = {"]
    for bucket in range(len(BUCKET_SCALES)):
        lines.append("    {")
        begin = bucket * variant_count
        for offset, size in ranges[begin:begin + variant_count]:
            lines.append(f"        {{ {offset}u, {size}u }},")
        lines.append("    },")
    lines += [
        "};",
        "inline Blob Get(u32 bucket, u32 variant)",
        "{",
        "    if (bucket >= BucketCount || variant >= VariantCount) return {};",
        "    const Range range = Ranges[bucket][variant];",
        "    return { Words + range.WordOffset, range.ByteSize };",
        "}",
        "} // namespace melonDS::DX12ShaderBlobs",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fxc", default=None, help="path to fxc.exe")
    parser.add_argument("--check-source-sync", action="store_true")
    args = parser.parse_args()

    digest = source_hash()
    if args.check_source_sync:
        try:
            with open(OUTPUT_PATH, "r", encoding="utf-8") as handle:
                first_lines = "".join(handle.readline() for _ in range(2))
        except FileNotFoundError:
            print(f"FAIL: generated DXBC table is missing: {OUTPUT_PATH}")
            return 1
        if f"Source SHA256: {digest}" not in first_lines:
            print("FAIL: generated DXBC is stale; run tools/dx12/compile-shaders.py")
            return 1
        print("DX12 generated shader source synchronization: PASS")
        return 0

    audit = load_audit_module()
    fxc = args.fxc or audit.find_fxc()
    if not fxc:
        print("FAIL: fxc.exe was not found", file=sys.stderr)
        return 1
    variants = audit.variants()
    blobs, ranges = compile_all(audit, fxc)
    output = render(blobs, ranges, digest, len(variants))
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(output)
    print(
        f"generated {len(blobs)} DXBC modules ({sum(len(blob) for blob in blobs)} bytes) "
        f"into {os.path.relpath(OUTPUT_PATH, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
