// Exact translations for upstream melonDS dialogs.
#include "MelonPrimeDialogsTranslationsEmulation.inc"
#include "MelonPrimeDialogsTranslationsNetworkInterface.inc"
#include "MelonPrimeDialogsTranslationsCheats.inc"
#include "MelonPrimeDialogsTranslationsPowerDateTime.inc"
#include "MelonPrimeDialogsTranslationsRomRam.inc"
#include "MelonPrimeDialogsTranslationsLan.inc"
#include "MelonPrimeDialogsTranslationsAbout.inc"
#include "MelonPrimeDialogsTranslationsFirmware.inc"
