#!/usr/bin/env python3
"""Write one deterministic Khronos Validation Layer profile.

The application deliberately keeps validation optional and does not bake a
debug-only policy into the renderer.  VK_LAYER_KHRONOS_validation reads this
file from the process working directory, so CI and manual validation runs can
select one profile without changing the normal runtime configuration.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PROFILES: dict[str, dict[str, str]] = {
    "core": {
        "validate_core": "true",
        "validate_sync": "false",
        "syncval_submit_time_validation": "false",
        "validate_best_practices": "false",
        "gpuav_enable": "false",
    },
    "sync": {
        "validate_core": "true",
        "validate_sync": "true",
        "syncval_submit_time_validation": "true",
        "validate_best_practices": "false",
        "gpuav_enable": "false",
    },
    "best-practices": {
        "validate_core": "true",
        "validate_sync": "false",
        "syncval_submit_time_validation": "false",
        "validate_best_practices": "true",
        "gpuav_enable": "false",
    },
    "gpu-av": {
        "validate_core": "true",
        "validate_sync": "false",
        "syncval_submit_time_validation": "false",
        "validate_best_practices": "false",
        "gpuav_enable": "true",
    },
}


def render(profile: str) -> str:
    settings = PROFILES[profile]
    lines = [
        "# Generated by tools/testing/vulkan-validation-profile.py",
        f"# profile = {profile}",
        "khronos_validation.report_flags = error,warn,perf,info",
        "khronos_validation.debug_action = VK_DBG_LAYER_ACTION_LOG_MSG",
    ]
    lines.extend(
        f"khronos_validation.{name} = {value}"
        for name, value in settings.items()
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=sorted(PROFILES), required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.profile), encoding="ascii", newline="\n")
    print(f"Vulkan validation profile written: {args.profile} -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
