#!/usr/bin/env python3
"""Build loc_chunk_2_extended.json with it, nl, pt, ru, zh, ko translations."""
import json
from pathlib import Path

# (it, nl, pt, ru, zh, ko) for each entry in loc_chunk_2_translated.json order
EXTRA = [
    ("Off", "Off", "Off", "Выкл.", "关闭", "꺼짐"),
    ("Copia output", "Uitvoer kopiëren", "Copiar saída", "Копировать вывод", "复制输出", "출력 복사"),
    ("Seleziona file font HUD", "HUD-lettertypebestand selecteren", "Selecionar arquivo de fonte HUD", "Выбрать файл шрифта HUD", "选择 HUD 字体文件", "HUD 글꼴 파일 선택"),
    ("Mod.", "Wijz.", "Alt.", "Изм.", "更改", "변경"),
    ("Normale", "Normaal", "Normal", "Обычный", "正常", "보통"),
    ("Generale", "Algemeen", "Geral", "Общий", "整体", "전체"),
    ("File di font (*.ttf *.otf *.ttc);;Tutti i file (*)", "Lettertypebestanden (*.ttf *.otf *.ttc);;Alle bestanden (*)", "Arquivos de fonte (*.ttf *.otf *.ttc);;Todos os arquivos (*)", "Файлы шрифтов (*.ttf *.otf *.ttc);;Все файлы (*)", "字体文件 (*.ttf *.otf *.ttc);;所有文件 (*)", "글꼴 파일 (*.ttf *.otf *.ttc);;모든 파일 (*)"),
    ("Apri ROM...", "ROM openen...", "Abrir ROM...", "Открыть ROM...", "打开 ROM...", "ROM 열기..."),
    ("Slot DS", "DS-sleuf", "Slot DS", "Слот DS", "DS 卡槽", "DS 슬롯"),
    ("Inserisci cartuccia add-on", "Add-on-cartridge invoeren", "Inserir cartucho add-on", "Вставить картридж add-on", "插入扩展卡带", "애드온 카트리지 삽입"),
    ("Annulla caricamento stato", "Statusladen ongedaan maken", "Desfazer carregamento de estado", "Отменить загрузку состояния", "撤销状态加载", "상태 불러오기 취소"),
    ("Stop", "Stop", "Parar", "Стоп", "停止", "정지"),
    ("Configura codici trucchi", "Cheatcodes instellen", "Configurar códigos de trapaça", "Настроить чит-коды", "设置作弊码", "치트 코드 설정"),
    ("Avvia nuova istanza", "Nieuwe instantie starten", "Iniciar nova instância", "Запустить новый экземпляр", "启动新实例", "새 인스턴스 실행"),
    ("Rotazione schermo", "Schermrotatie", "Rotação de tela", "Поворот экрана", "屏幕旋转", "화면 회전"),
    ("Orizzontale", "Horizontaal", "Horizontal", "Горизонтально", "横向", "가로"),
    ("Enfatizza schermo superiore", "Bovenste scherm benadrukken", "Enfatizar tela superior", "Выделить верхний экран", "强调上屏", "상단 화면 강조"),
    ("Proporzioni", "Beeldverhouding", "Proporção de tela", "Соотношение сторон", "宽高比", "화면 비율"),
    ("Impostazioni emulatore", "Emulatorinstellingen", "Configurações do emulador", "Настройки эмулятора", "模拟器设置", "에뮬레이터 설정"),
    ("Impostazioni audio", "Audio-instellingen", "Configurações de áudio", "Настройки звука", "音频设置", "오디오 설정"),
    ("Impostazioni percorsi", "Padinstellingen", "Configurações de caminhos", "Настройки путей", "路径设置", "경로 설정"),
    ("Impostazioni MelonPrime", "MelonPrime-instellingen", "Configurações do MelonPrime", "Настройки MelonPrime", "MelonPrime 设置", "MelonPrime 설정"),
    ("Aiuto", "Help", "Ajuda", "Справка", "帮助", "도움말"),
    ("Controlli 2", "Besturing 2", "Controles 2", "Управление 2", "操作 2", "조작 2"),
    ("IMPOSTAZIONI INPUT", "INVOERINSTELLINGEN", "CONFIGURAÇÕES DE ENTRADA", "НАСТРОЙКИ ВВОДА", "输入设置", "입력 설정"),
    ("PROPORZIONI IN-GIOCO", "BEELDVERHOUDING IN SPEL", "PROPORÇÃO DE TELA NO JOGO", "СООТНОШЕНИЕ СТОРОН В ИГРЕ", "游戏内宽高比", "게임 내 화면 비율"),
    ("DISABILITA FUNZIONI", "FUNCTIES UITSCHAKELEN", "DESATIVAR RECURSOS", "ОТКЛЮЧИТЬ ФУНКЦИИ", "禁用功能", "기능 비활성화"),
    ("APPLICA LICENZA", "LICENTIE TOEPASSEN", "APLICAR LICENÇA", "ПРИМЕНИТЬ ЛИЦЕНЗИЮ", "应用许可证", "라이선스 적용"),
    ("FONT HUD", "HUD-LETTERTYPE", "FONTE HUD", "ШРИФТ HUD", "HUD 字体", "HUD 글꼴"),
    ("COLORE OSD IN-GIOCO", "OSD-KLEUR IN SPEL", "COR OSD NO JOGO", "ЦВЕТ OSD В ИГРЕ", "游戏内 OSD 颜色", "게임 내 OSD 색상"),
    ("[Metroid] (S) Indietro", "[Metroid] (S) Achteruit", "[Metroid] (S) Recuar", "[Metroid] (S) Назад", "[Metroid] (S) 后退", "[Metroid] (S) 후진"),
    ("[Metroid] (Mouse destro) Zoom Imperialist, zoom mappa indietro, Morph Ball Boost", "[Metroid] (Rechtermuisknop) Imperialist-zoom, kaart uitzoomen, Morph Ball Boost", "[Metroid] (Botão direito) Zoom Imperialist, diminuir mapa, impulso Morph Ball", "[Metroid] (ПКМ) Зум Imperialist, отдаление карты, Morph Ball Boost", "[Metroid] (鼠标右键) Imperialist 缩放、地图缩小、变形球加速", "[Metroid] (마우스 오른쪽) Imperialist 줌, 맵 축소, Morph Ball Boost"),
    ("[Metroid] (Mouse 4, laterale inferiore) Arma missile", "[Metroid] (Muis 4, onderste zijknop) Wapen raket", "[Metroid] (Mouse 4, lateral inferior) Arma míssil", "[Metroid] (Кнопка 4, нижняя боковая) Оружие ракета", "[Metroid] (鼠标 4/侧键下) 导弹武器", "[Metroid] (마우스 4/측면 하단) 미사일 무기"),
    ("[Metroid] (5) Arma 5: Battlehammer", "[Metroid] (5) Wapen 5: Battlehammer", "[Metroid] (5) Arma 5: Battlehammer", "[Metroid] (5) Оружие 5: Battlehammer", "[Metroid] (5) 武器 5：Battlehammer", "[Metroid] (5) 무기 5: Battlehammer"),
    ("[Metroid] (PgDown) Riduci sensibilità mira", "[Metroid] (PgDown) Richtgevoeligheid verlagen", "[Metroid] (PgDown) Diminuir sensibilidade de mira", "[Metroid] (PgDown) Уменьшить чувствительность прицела", "[Metroid] (PgDown) 降低瞄准灵敏度", "[Metroid] (PgDown) 조준 감도 낮추기"),
    ("[Metroid] (X) UI destra (Freccia destra avventura / Licenza Hunter R)", "[Metroid] (X) UI rechts (Avontuur pijl rechts / Hunter-licentie R)", "[Metroid] (X) UI direita (Seta direita aventura / Licença Hunter R)", "[Metroid] (X) UI вправо (Стрелка вправо приключения / Лицензия Hunter R)", "[Metroid] (X) UI 右 (冒险右/猎人许可证 R)", "[Metroid] (X) UI 오른쪽 (어드벤처 오른쪽/헌터 라이선스 R)"),
    ("Sensibilità MPH (predefinito: -3)", "MPH-gevoeligheid (standaard: -3)", "Sensibilidade MPH (padrão: -3)", "Чувствительность MPH (по умолчанию: -3)", "MPH 灵敏度 (默认: -3)", "MPH 감도 (기본값: -3)"),
    ("Mira istantanea", "Directe richtvolging", "Seguimento de mira instantâneo", "Мгновенное слежение прицела", "即时瞄准跟随", "즉시 조준 추적"),
    ("Sblocca tutti i cacciatori/mappe/sound test/galleria (Modifica un'impostazione in MPH e salva per aggiornare i dati. Deseleziona questa opzione dopo il salvataggio)", "Alle jagers/kaarten/soundtest/galerij ontgrendelen (Wijzig een instelling in MPH en sla op om gegevens bij te werken. Schakel deze optie uit na het opslaan)", "Desbloquear todos os caçadores/mapas/teste de som/galeria (Altere uma configuração no MPH e salve para atualizar os dados. Desmarque esta opção após salvar)", "Разблокировать всех охотников/карты/звуковой тест/галерею (Измените настройку в MPH и сохраните для обновления данных. Снимите эту опцию после сохранения)", "解锁全部猎人/地图/音效测试/画廊 (在 MPH 中更改设置并保存以更新存档。保存后请取消勾选此选项)", "모든 헌터/맵/사운드 테스트/갤러리 잠금 해제 (MPH에서 설정을 변경하고 저장하면 데이터가 반영됩니다. 저장 후 이 옵션을 해제하세요)"),
    ("Disabilita smoothing mira MPH (Disabilita lo smoothing della mira in gioco. Nota: la sensibilità sarà ridotta al 25% in modalità stylus)", "MPH-richtgladmaking uitschakelen (Schakelt richtgladmaking in het spel uit. Opmerking: gevoeligheid wordt verlaagd naar 25% in stylusmodus)", "Desativar suavização de mira MPH (Desativa a suavização de mira no jogo. Nota: a sensibilidade será reduzida a 25% no modo stylus)", "Отключить сглаживание прицела MPH (Отключает сглаживание прицела в игре. Примечание: чувствительность снижается до 25% в режиме стилуса)", "禁用 MPH 瞄准平滑 (禁用游戏内瞄准平滑。注意：触控笔模式下灵敏度将降至 25%)", "MPH 조준 스무딩 비활성화 (게임 내 조준 스무딩을 비활성화합니다. 참고: 스타일러스 모드에서 감도가 25%로 줄어듭니다)"),
    ("Abilita overlay bordi input immediato", "Directe invoerrand-overlay inschakelen", "Ativar sobreposição de bordas de entrada imediata", "Включить наложение мгновенных границ ввода", "启用即时输入边缘叠加", "즉시 입력 엣지 오버레이 활성화"),
    ("Modalità sincronizzazione schermo", "Schermsynchronisatiemodus", "Modo de sincronização de tela", "Режим синхронизации экрана", "屏幕同步模式", "화면 동기화 모드"),
    ("Modalità proporzioni", "Beeldverhoudingsmodus", "Modo de proporção de tela", "Режим соотношения сторон", "宽高比模式", "화면 비율 모드"),
    ("21:9", "21:9", "21:9", "21:9", "21:9", "21:9"),
    ("Fix bitset attivo Wi-Fi amico/rivale (v2)", "Fix actieve Wi-Fi-bitset vriend/rivaal (v2)", "Correção de bitset ativo Wi-Fi amigo/rival (v2)", "Исправление битсета активного Wi-Fi друга/соперника (v2)", "好友/对手 Wi-Fi 激活位集修复 (v2)", "친구/라이벌 Wi-Fi 활성 비트셋 수정 (v2)"),
    ("Notifica danni viola", "Schademelding paars", "Notificação de dano roxa", "Уведомление об уроне фиолетовое", "伤害通知紫色", "피해 알림 보라색"),
    ("Reimposta valori sensibilità", "Gevoeligheidswaarden resetten", "Redefinir valores de sensibilidade", "Сбросить значения чувствительности", "重置灵敏度值", "감도 값 초기화"),
    ("Applica volume musica", "Muziekvolume toepassen", "Aplicar volume da música", "Применить громкость музыки", "应用音乐音量", "음악 볼륨 적용"),
    ("Rosso (JP,KR)", "Rood (JP,KR)", "Vermelho (JP,KR)", "Красный (JP,KR)", "红 (JP,KR)", "빨강 (JP,KR)"),
    ("Disabilitato (vanilla 25)", "Uitgeschakeld (vanilla 25)", "Desativado (vanilla 25)", "Отключено (vanilla 25)", "禁用 (原版 25)", "비활성화 (바닐라 25)"),
    ("Per danno — Medio", "Per schade — Gemiddeld", "Por dano — Médio", "За урон — Средний", "按伤害 — 中", "피해별 — 보통"),
    ("Le funzioni in questa sezione sono ancora in sviluppo e non sono pronte per il rilascio pubblico. Potrebbero essere rilasciate o meno.", "Functies in dit gedeelte zijn nog in ontwikkeling en niet klaar voor openbare release. Ze worden mogelijk wel of niet uitgebracht.", "Os recursos desta seção ainda estão em desenvolvimento e não estão prontos para lançamento público. Podem ou não ser lançados.", "Функции в этом разделе ещё в разработке и не готовы к публичному выпуску. Они могут быть выпущены или нет.", "此部分功能仍在开发中，尚未准备好公开发布。将来可能会发布，也可能不会。", "이 섹션의 기능은 아직 개발 중이며 공개 출시 준비가 되지 않았습니다. 출시 여부는 미정입니다."),
    ("Selezionato: usa l'assegnazione zoom in gioco del preset controlli del giocatore. Deselezionato: usa il percorso fisso del pulsante R precedente.", "Aangevinkt: gebruik de huidige in-game zoomtoets uit het besturingspreset van de speler. Uitgevinkt: gebruik het oudere vaste R-knoppad.", "Marcado: usa a atribuição de zoom no jogo do preset de controles do jogador. Desmarcado: usa o caminho fixo antigo do botão R.", "Включено: используется текущая привязка зума в игре из пресета управления игрока. Выключено: используется старый фиксированный путь кнопки R.", "勾选：使用玩家控制预设中的当前游戏内缩放绑定。取消勾选：使用旧的固定 R 键路径。", "선택: 플레이어 조작 프리셋의 현재 게임 내 줌 바인딩 사용. 해제: 이전 고정 R 버튼 경로 사용."),
    ("Chiave impostazione: Metroid.Volume.Music (0–9)", "Instellingssleutel: Metroid.Volume.Music (0–9)", "Chave de configuração: Metroid.Volume.Music (0–9)", "Ключ настройки: Metroid.Volume.Music (0–9)", "设置键: Metroid.Volume.Music (0–9)", "설정 키: Metroid.Volume.Music (0–9)"),
    ("Solo Windows. Si applica solo mentre lo schermo inferiore viene effettivamente disegnato. Premi ESC per rilasciare il cursore.", "Alleen Windows. Geldt alleen terwijl het onderste scherm daadwerkelijk wordt getekend. Druk op ESC om de cursor vrij te geven.", "Somente Windows. Aplica-se apenas enquanto a tela inferior está sendo desenhada. Pressione ESC para liberar o cursor.", "Только Windows. Применяется только пока нижний экран действительно отрисовывается. Нажмите ESC, чтобы освободить курсор.", "仅限 Windows。仅在下屏实际绘制时生效。按 ESC 释放光标。", "Windows 전용. 하단 화면이 실제로 그려지는 동안에만 적용됩니다. ESC를 눌러 커서를 해제하세요."),
    ("Nascondi questa finestra ed entra nell'editor interattivo posizione HUD", "Dit dialoogvenster verbergen en interactieve HUD-positie-editor openen", "Ocultar esta caixa de diálogo e entrar no editor interativo de posição HUD", "Скрыть это окно и войти в интерактивный редактор позиции HUD", "隐藏此对话框并进入交互式 HUD 位置编辑器", "이 대화 상자를 숨기고 대화형 HUD 위치 편집기로 들어가기"),
    ("— HUD comune —", "— Gemeenschappelijke HUD —", "— HUD comum —", "— Общий HUD —", "— 通用 HUD —", "— 공통 HUD —"),
    ("Nascondi HP", "HP verbergen", "Ocultar HP", "Скрыть HP", "隐藏 HP", "HP 숨기기"),
    ("Nascondi punteggio: Prime Hunter", "Score verbergen: Prime Hunter", "Ocultar pontuação: Prime Hunter", "Скрыть счёт: Prime Hunter", "隐藏分数: Prime Hunter", "점수 숨기기: Prime Hunter"),
    ("Scala testo (base %)", "Tekstschaal (basis %)", "Escala de texto (base %)", "Масштаб текста (база %)", "文字缩放 (基准 %)", "텍스트 크기 (기준 %)"),
    ("Limite scala automatica indicatore %", "Auto-schaal meterplafond %", "Limite de escala automática do medidor %", "Предел авто-масштаба индикатора %", "自动缩放指示条上限 %", "자동 크기 조절 게이지 상한 %"),
    ("Corsivo", "Cursief", "Itálico", "Курсив", "斜体", "기울임"),
    ("Fase zoom", "Zoomfase", "Estágio de zoom", "Стадия зума", "缩放阶段", "줌 단계"),
    ("Mirino zoom", "Zoomvizier", "Visor de zoom", "Прицел зума", "缩放瞄准镜", "줌 스코프"),
    ("Punto centrale mirino", "Vizier middenpunt", "Ponto central do visor", "Центральная точка прицела", "瞄准镜中心点", "스코프 중앙 점"),
    ("Velocità transizione zoom %", "Zoomovergangssnelheid %", "Velocidade de transição do zoom %", "Скорость перехода зума %", "缩放过渡速度 %", "줌 전환 속도 %"),
    ("Intensità impulso %", "Pulssterkte %", "Intensidade do pulso %", "Сила пульсации %", "脉冲强度 %", "펄스 강도 %"),
    ("A fasi", "Gefaseerd", "Por estágios", "Поэтапный", "分阶段", "단계별"),
    ("Digitale", "Digitaal", "Digital", "Цифровой", "数字", "디지털"),
    ("Ottica da cecchino", "Scherpschutteroptiek", "Óptica de sniper", "Снайперская оптика", "狙击光学", "스나이퍼 광학"),
    ("Colore contorno", "Omtrekkleur", "Cor do contorno", "Цвет контура", "轮廓颜色", "외곽선 색상"),
    ("Colore punto personalizzato", "Aangepaste puntkleur", "Cor de ponto personalizada", "Пользовательский цвет точки", "自定义点颜色", "사용자 지정 점 색상"),
    ("Cerchio", "Cirkel", "Círculo", "Круг", "圆形", "원"),
    ("Interno", "Binnen", "Interior", "Внутренний", "内侧", "내부"),
    ("Mostra testo", "Tekst tonen", "Mostrar texto", "Показать текст", "显示文字", "텍스트 표시"),
    ("Lunghezza", "Lengte", "Comprimento", "Длина", "长度", "길이"),
    ("Offset", "Offset", "Deslocamento", "Смещение", "偏移", "오프셋"),
    ("In alto al centro", "Boven midden", "Superior central", "Верх по центру", "上中", "상단 중앙"),
    ("In basso a sinistra", "Linksonder", "Inferior esquerda", "Внизу слева", "左下", "왼쪽 하단"),
    ("Centro destra", "Midden rechts", "Centro direita", "По центру справа", "右中", "오른쪽 중앙"),
    ("Centro", "Midden", "Centro", "По центру", "中央", "중앙"),
    ("Sotto", "Onder", "Abaixo", "Ниже", "下方", "아래"),
    ("Oriz.", "Horiz.", "Horiz.", "Гориз.", "横", "가로"),
    ("Indicatore→Testo", "Meter→Tekst", "Medidor→Texto", "Индикатор→Текст", "指示条→文字", "게이지→텍스트"),
    ("Modo posizione", "Positiemodus", "Modo de posição", "Режим позиции", "位置模式", "위치 모드"),
    ("Indicatore Y", "Meter Y", "Medidor Y", "Индикатор Y", "指示条 Y", "게이지 Y"),
    ("Prefisso", "Voorvoegsel", "Prefixo", "Префикс", "前缀", "접두사"),
    ("Orientamento", "Orientatie", "Orientação", "Ориентация", "方向", "방향"),
    ("Posizione icona", "Pictogrampositie", "Posição do ícone", "Положение значка", "图标位置", "아이콘 위치"),
    ("Layout", "Lay-out", "Layout", "Макет", "布局", "레이아웃"),
    ("Pos. etichetta", "Labelpos.", "Pos. rótulo", "Поз. метки", "标签位置", "라벨 위치"),
    ("Etichetta: Punti", "Label: Punten", "Rótulo: Pontos", "Метка: Очки", "标签: 分数", "라벨: 점수"),
    ("Battaglia", "Gevecht", "Batalha", "Бой", "战斗", "배틀"),
    ("Etichetta", "Label", "Rótulo", "Метка", "标签", "라벨"),
    ("Colore etichetta", "Labelkleur", "Cor do rótulo", "Цвет метки", "标签颜色", "라벨 색상"),
    ("Colore separatore: Generale", "Scheidingskleur: Algemeen", "Cor de separação: Geral", "Цвет разделителя: Общий", "分隔颜色: 整体", "구분 색상: 전체"),
    ("Sovrapposizione colore", "Kleuroverlay", "Sobreposição de cor", "Цветовое наложение", "颜色叠加", "색상 오버레이"),
    ("Dest. X", "Best. X", "Dest. X", "Цел. X", "显示 X", "표시 X"),
    ("Padding", "Padding", "Preenchimento", "Отступ", "边距", "여백"),
    ("Colore evidenziazione", "Highlightkleur", "Cor de destaque", "Цвет выделения", "高亮颜色", "하이라이트 색상"),
    ("Offset evidenziazione sinistra", "Highlight-offset links", "Deslocamento esquerdo de destaque", "Смещение выделения влево", "高亮左偏移", "하이라이트 왼쪽 오프셋"),
    ("Offset dimensione destra", "Grootte-offset rechts", "Deslocamento direito de tamanho", "Смещение размера вправо", "尺寸右偏移", "크기 오른쪽 오프셋"),
    ("Padding HL", "HL-padding", "Preenchimento HL", "Отступ HL", "HL 边距", "HL 여백"),
    ("Ofs. inf. HL", "HL-offset onder", "Desloc. inf. HL", "Смещ. низ HL", "HL 下偏移", "HL 하단 오프셋"),
    ("Indicatore HP", "HP-meter", "Medidor de HP", "Индикатор HP", "HP 指示条", "HP 게이지"),
    ("Colore etichetta munizioni per valore", "Munitielabelkleur op waarde", "Cor do rótulo de munição por valor", "Цвет метки боеприпасов по значению", "弹药标签颜色 (按数值)", "탄약 라벨 색상 (값 연동)"),
    ("Arma/Munizioni", "Wapen/Munitie", "Arma/Munição", "Оружие/Боеприпасы", "武器/弹药", "무기/탄약"),
    ("Evidenziazione inventario armi", "Wapeninventaris-highlight", "Destaque do inventário de armas", "Выделение инвентаря оружия", "武器栏高亮", "무기 인벤토리 하이라이트"),
    ("Etichette punteggio", "Scorelabels", "Rótulos de pontuação", "Метки счёта", "分数标签", "점수 라벨"),
    ("Contorno rango", "Rangomtrek", "Contorno de rank", "Контур ранга", "排名轮廓", "순위 외곽선"),
    ("Bomba", "Bom", "Bomba", "Бомба", "炸弹", "폭탄"),
    ("Radar", "Radar", "Radar", "Radar", "雷达", "레이더"),
    ("Arma\nIcona", "Wpn\nPictogram", "Arma\nÍcone", "Оруж.\nЗначок", "武器\n图标", "무기\n아이콘"),
    ("punti", "punten", "pontos", "очки", "得分", "점수"),
    ("Abilita colore separato", "Aparte kleur inschakelen", "Ativar cor separada", "Включить отдельный цвет", "启用单独颜色", "별도 색상 활성화"),
    ("Ritorna alla base", "Terug naar basis", "Retornar à base", "Вернуться на базу", "返回基地", "기지로 복귀"),
    ("Reset Octo", "Octo-reset", "Redefinir Octo", "Сброс Octo", "Octo 重置", "Octo 리셋"),
    ("Slot: Cattura nodo  [flags=0x11]", "Slot: Knooppunt vastleggen  [flags=0x11]", "Slot: Captura de nó  [flags=0x11]", "Слот: Захват узла  [flags=0x11]", "槽位: 节点占领 [flags=0x11]", "슬롯: 노드 점령 [flags=0x11]"),
    ("Applicato una volta alla chiusura delle impostazioni ai messaggi attualmente visualizzati (flags=0x01).\nI nuovi messaggi usano i colori letterali individuali sopra (Nessuna munizione / Ritorna alla base / Octo ...).", "Eenmalig toegepast bij sluiten van instellingen op momenteel weergegeven berichten (flags=0x01).\nNieuwe berichten gebruiken hun individuele kleuren hierboven (Geen munitie / Terug naar basis / Octo ...).", "Aplicado uma vez ao fechar as configurações às mensagens exibidas (flags=0x01).\nNovas mensagens usam suas cores individuais acima (Sem munição / Retornar à base / Octo ...).", "Применяется один раз при закрытии настроек к текущим сообщениям (flags=0x01).\nНовые сообщения используют свои индивидуальные цвета выше (Нет боеприпасов / Вернуться на базу / Octo ...).", "关闭设置时对当前显示的消息应用一次 (flags=0x01)。\n新消息使用上方各自的字面颜色 (无弹药 / 返回基地 / Octo ...)。", "설정을 닫을 때 현재 표시 중인 메시지에 한 번 적용됩니다 (flags=0x01).\n새 메시지는 위의 개별 색상을 사용합니다 (탄약 없음 / 기지로 복귀 / Octo ...)."),
    ("Colore  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / torretta)", "Kleur  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / turret)", "Cor  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / torreta)", "Цвет  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / турель)", "颜色  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / 炮塔)", "색상  (HEADSHOT! / FACE OFF! / RETURN TO BATTLE! / COWARD DETECTED / 터렛)"),
    ("Giallo", "Geel", "Amarelo", "Жёлтый", "黄", "노랑"),
    ("Arancione", "Oranje", "Laranja", "Оранжевый", "橙", "주황"),
    ("Contorno HUD Spire", "Spire HUD-omtrek", "Contorno HUD Spire", "Контур HUD Spire", "Spire HUD 轮廓", "Spire HUD 외곽선"),
    ("Mirino Sylux", "Sylux richtkruis", "Mira Sylux", "Прицел Sylux", "Sylux 准星", "Sylux 조준선"),
    ("OSD munizioni esaurite rosso", "OSD geen munitie rood", "OSD sem munição vermelho", "OSD нет боеприпасов красный", "OSD 无弹药红色", "OSD 탄약 없음 빨강"),
    ("Battlehammer", "Battlehammer", "Battlehammer", "Battlehammer", "Battlehammer", "Battlehammer"),
    ("Shock Coil", "Shock Coil", "Shock Coil", "Shock Coil", "Shock Coil", "Shock Coil"),
    ("Colore MSL", "MSL-kleur", "Cor MSL", "Цвет MSL", "MSL 颜色", "MSL 색상"),
    ("Colore SCL", "SCL-kleur", "Cor SCL", "Цвет SCL", "SCL 颜色", "SCL 색상"),
    ("Standard", "Standaard", "Padrão", "Стандартный", "标准", "표준"),
    ("Nero", "Zwart", "Preto", "Чёрный", "黑", "검정"),
    ("Soglia 4 (%)", "Drempel 4 (%)", "Limite 4 (%)", "Порог 4 (%)", "阈值 4 (%)", "임계값 4 (%)"),
    ("Colore 3", "Kleur 3", "Cor 3", "Цвет 3", "颜色 3", "색상 3"),
    ("Output aggiornato dalle impostazioni HUD personalizzate attuali.", "Uitvoer ververst vanuit huidige aangepaste HUD-instellingen.", "Saída atualizada a partir das configurações atuais do HUD personalizado.", "Вывод обновлён из текущих настроек пользовательского HUD.", "已从当前自定义 HUD 设置刷新输出。", "현재 사용자 HUD 설정에서 출력을 새로고침했습니다."),
    ("Il codice HUD personalizzato incollato non è una tabella TOML.", "De geplakte aangepaste HUD-code is geen TOML-tabel.", "O código HUD personalizado colado não é uma tabela TOML.", "Вставленный код пользовательского HUD не является таблицей TOML.", "粘贴的自定义 HUD 代码不是 TOML 表。", "붙여넣은 사용자 HUD 코드가 TOML 테이블이 아닙니다."),
    ("Usa nuovo metodo per zoom", "Nieuwe zoommethode gebruiken", "Usar novo método de zoom", "Использовать новый метод зума", "使用新缩放方式", "줌에 새 방식 사용"),
    ("Impostazioni audio - melonDS", "Audio-instellingen - melonDS", "Configurações de áudio - melonDS", "Настройки звука - melonDS", "音频设置 - melonDS", "오디오 설정 - melonDS"),
    ("Modalità DSi", "DSi-modus", "Modo DSi", "Режим DSi", "DSi 模式", "DSi 모드"),
    ("Avvia gioco direttamente", "Spel direct starten", "Iniciar jogo diretamente", "Запустить игру напрямую", "直接启动游戏", "게임 직접 실행"),
    ("Firmware DS:", "DS-firmware:", "Firmware DS:", "Прошивка DS:", "DS 固件:", "DS 펌웨어:"),
    ("Abilita scheda SD DSi", "DSi SD-kaart inschakelen", "Ativar cartão SD DSi", "Включить SD-карту DSi", "启用 DSi SD 卡", "DSi SD 카드 활성화"),
    ("DSP HLE", "DSP HLE", "DSP HLE", "DSP HLE", "DSP HLE", "DSP HLE"),
    ("Memoria veloce", "Snel geheugen", "Memória rápida", "Быстрая память", "快速内存", "고속 메모리"),
    ("Interrompi all'avvio", "Pauzeren bij opstarten", "Pausar na inicialização", "Остановка при запуске", "启动时中断", "시작 시 중단"),
    ("Auto", "Auto", "Auto", "Авто", "自动", "자동"),
    ("Software", "Software", "Software", "Программный", "软件", "소프트웨어"),
    ("Intervallo VSync:", "VSync-interval:", "Intervalo VSync:", "Интервал VSync:", "VSync 间隔:", "VSync 간격:"),
    ("Configura fotocamera emulata:", "Geëmuleerde camera configureren:", "Configurar câmera emulada:", "Настроить эмулируемую камеру:", "配置模拟摄像头:", "에뮬레이트 카메라 설정:"),
    ("File immagine:", "Afbeeldingsbestand:", "Arquivo de imagem:", "Файл изображения:", "图像文件:", "이미지 파일:"),
    ("Uscita audio", "Audio-uitvoer", "Saída de áudio", "Вывод звука", "音频输出", "오디오 출력"),
    ("Sincronizza con volume DSi", "Synchroniseren met DSi-volume", "Sincronizar com volume DSi", "Синхронизировать с громкостью DSi", "与 DSi 音量同步", "DSi 볼륨과 동기화"),
    ("Gaussiano (SNES)", "Gaussisch (SNES)", "Gaussiano (SNES)", "Гауссов (SNES)", "高斯 (SNES)", "가우시안 (SNES)"),
    ("Rumore soffio", "Blazgeluid", "Ruído de sopro", "Шум дуновения", "吹气噪声", "불기 노이즈"),
    ("Reimposta", "Resetten", "Redefinir", "Сброс", "重置", "초기화"),
    ("Attiva/disattiva slow motion", "Slow motion in-/uitschakelen", "Alternar câmera lenta", "Переключить замедление", "切换慢动作", "슬로 모션 전환"),
    ("Scambia schermi", "Schermen wisselen", "Trocar telas", "Поменять экраны", "交换上下屏", "화면 교환"),
    ("Attiva/disattiva muto audio", "Dempen in-/uitschakelen", "Alternar silenciar áudio", "Переключить отключение звука", "切换音频静音", "오디오 음소거 전환"),
    ("Solo istanza attiva", "Alleen actieve instantie", "Somente instância ativa", "Только активный экземпляр", "仅活动实例", "활성 인스턴스만"),
    ("Modalità indiretta (usa libslirp, consigliato)", "Indirecte modus (gebruikt libslirp, aanbevolen)", "Modo indireto (usa libslirp, recomendado)", "Косвенный режим (использует libslirp, рекомендуется)", "间接模式 (使用 libslirp，推荐)", "간접 모드 (libslirp 사용, 권장)"),
    ("Indirizzo IP:", "IP-adres:", "Endereço IP:", "IP-адрес:", "IP 地址:", "IP 주소:"),
    ("Nome utente:", "Gebruikersnaam:", "Nome de usuário:", "Имя пользователя:", "用户名:", "사용자 이름:"),
    ("Impostazioni rete", "Netwerkinstellingen", "Configurações de rede", "Настройки сети", "网络设置", "네트워크 설정"),
    ("Predefinito di sistema", "Systeemstandaard", "Padrão do sistema", "Системный по умолчанию", "系统默认", "시스템 기본값"),
    ("Silenzia audio durante avanzamento rapido", "Audio dempen tijdens vooruitspoelen", "Silenciar áudio ao avançar rápido", "Отключить звук при ускорении", "快进时静音", "빨리 감기 중 오디오 음소거"),
    ("Slow-Mo", "Slow-Mo", "Slow-Mo", "Замедление", "慢动作", "슬로 모션"),
    ("2x", "2x", "2x", "2x", "2x", "2x"),
    ("Percorso stati salvati:", "Pad voor savestates:", "Caminho de estados salvos:", "Путь сохранений состояния:", "即时存档路径:", "상태 저장 경로:"),
    ("Nuovo codice AR", "Nieuwe AR-code", "Novo código AR", "Новый AR-код", "新建 AR 代码", "새 AR 코드"),
    ("Nome:", "Naam:", "Nome:", "Имя:", "名称:", "이름:"),
    ("Gestione alimentazione - melonDS", "Energiebeheer - melonDS", "Gerenciamento de energia - melonDS", "Управление питанием - melonDS", "电源管理 - melonDS", "전원 관리 - melonDS"),
    ("Piena", "Vol", "Completa", "Полная", "满电", "가득"),
    ("Data e ora", "Datum en tijd", "Data e hora", "Дата и время", "日期和时间", "날짜 및 시간"),
    ("Info ROM - melonDS", "ROM-info - melonDS", "Info da ROM - melonDS", "Информация о ROM - melonDS", "ROM 信息 - melonDS", "ROM 정보 - melonDS"),
    ("Titolo tedesco:", "Duitse titel:", "Título alemão:", "Немецкое название:", "德语标题:", "독일어 제목:"),
    ("Binari ARM7 e ARM9", "ARM7- en ARM9-binaries", "Binários ARM7 e ARM9", "Бинарные файлы ARM7 и ARM9", "ARM7/ARM9 二进制", "ARM7/ARM9 바이너리"),
    ("Offset ROM ARM7: ", "ARM7 ROM-offset: ", "Deslocamento ROM ARM7: ", "Смещение ROM ARM7: ", "ARM7 ROM 偏移: ", "ARM7 ROM 오프셋: "),
    ("Offset FNT:", "FNT-offset:", "Deslocamento FNT:", "Смещение FNT:", "FNT 偏移:", "FNT 오프셋:"),
    ("Titolo gioco:", "Speltitel:", "Título do jogo:", "Название игры:", "游戏标题:", "게임 제목:"),
    ("Salva icona animata", "Geanimeerd pictogram opslaan", "Salvar ícone animado", "Сохранить анимированный значок", "保存动画图标", "애니메이션 아이콘 저장"),
    ("2 byte", "2 bytes", "2 bytes", "2 байта", "2 字节", "2바이트"),
    ("Trovato:", "Gevonden:", "Encontrado:", "Найдено:", "检出:", "발견:"),
    ("Connetti", "Verbinden", "Conectar", "Подключить", "连接", "연결"),
    ("Giocatori", "Spelers", "Jogadores", "Игроки", "玩家", "플레이어"),
    ("Inserisci un nome giocatore.", "Voer een spelersnaam in.", "Digite um nome de jogador.", "Введите имя игрока.", "请输入玩家名称。", "플레이어 이름을 입력하세요."),
    ("Visita il &sito web", "Bezoek de &website", "Visitar o &site", "Посетить &сайт", "访问网站(&W)", "웹사이트(&W) 방문"),
    ("Marrone", "Bruin", "Marrom", "Коричневый", "茶色", "갈색"),
    ("Lime", "Limoen", "Lima", "Лаймовый", "青柠", "라임"),
    ("Blu", "Blauw", "Azul", "Синий", "蓝", "파랑"),
    ("Francese", "Frans", "Francês", "Французский", "法语", "프랑스어"),
    ("Gennaio", "Januari", "Janeiro", "Январь", "1 月", "1월"),
    ("Giugno", "Juni", "Junho", "Июнь", "6 月", "6월"),
    ("Novembre", "November", "Novembro", "Ноябрь", "11 月", "11월"),
]

def main():
    src = Path(__file__).parent / "loc_chunk_2_translated.json"
    dst = Path(__file__).parent / "loc_chunk_2_extended.json"

    with open(src, encoding="utf-8") as f:
        entries = json.load(f)

    if len(entries) != len(EXTRA):
        raise SystemExit(f"Count mismatch: {len(entries)} entries vs {len(EXTRA)} translations")

    out = []
    for entry, (it, nl, pt, ru, zh, ko) in zip(entries, EXTRA):
        row = {
            "en": entry["en"],
            "ja": entry["ja"],
            "de": entry["de"],
            "es": entry["es"],
            "fr": entry["fr"],
            "it": it,
            "nl": nl,
            "pt": pt,
            "ru": ru,
            "zh": zh,
            "ko": ko,
        }
        if "section" in entry:
            row["section"] = entry["section"]
        out.append(row)

    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Wrote {len(out)} entries to {dst}")

if __name__ == "__main__":
    main()
