#!/usr/bin/env python3
"""Generate the pinned Sapphire GPU2D HBlank event block (S79-4)."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LIB_ROOT = Path(r"C:\Users\Admin\Documents\git\melonDS-android-lib")
OUTPUT_DIR = REPO_ROOT / "src" / "SapphireGenerated"
GENERATED_INC = OUTPUT_DIR / "SapphireGpu2DHBlankCore.inc"
MANIFEST_PATH = OUTPUT_DIR / "SapphireGpu2DEventBlockManifest.json"
PINNED_COMMIT = "d77944275fa61f9b79cfcead2c3e98993429a023"

NORMALIZED_SEQUENCE = [
    "GPU2D_Renderer->DrawScanline(line, &GPU2D_A)",
    "GPU2D_Renderer->DrawScanline(line, &GPU2D_B)",
    "GPU2D_Renderer->DrawSprites(line+1, &GPU2D_A)",
    "GPU2D_Renderer->DrawSprites(line+1, &GPU2D_B)",
    "NDS.CheckDMAs(0, 0x02)",
]


def lib_root() -> Path:
    env = os.environ.get("SAPPHIRE_ANDROID_LIB_ROOT")
    return Path(env) if env else DEFAULT_LIB_ROOT


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract_upstream_block(gpu_cpp: str) -> str:
    match = re.search(
        r"void GPU::StartHBlank\(u32 line\) noexcept\s*\{([\s\S]*?)^}",
        gpu_cpp,
        re.MULTILINE,
    )
    if match is None:
        raise ValueError("StartHBlank not found in upstream GPU.cpp")

    body = match.group(1)
    vcount_block = re.search(
        r"if \(VCount < 192\)\s*\{([\s\S]*?)\n    \}\n    else if \(VCount == 215\)",
        body,
    )
    if vcount_block is None:
        raise ValueError("VCount < 192 block not found in upstream StartHBlank")

    return vcount_block.group(1)


def normalize_block(text: str) -> list[str]:
    lines: list[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("//"):
            continue
        stripped = re.sub(r"\s+", " ", stripped)
        stripped = stripped.rstrip(";")
        stripped = stripped.replace("line + 1", "line+1")
        if "GPU2D_Renderer->" in stripped or stripped.startswith("NDS.CheckDMAs"):
            lines.append(stripped)
    return lines


def build_generated_inc() -> str:
    return """// Generated by tools/generate_sapphire_gpu2d_event_block.py — do not edit.
if (line < 192)
{
    SAPPHIRE_GPU2D_HBLANK_TRACE_BEFORE_UNITA_SCANLINE(line);
    GPU2D_Renderer->DrawScanline(line, &GPU2D_A);
    SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_UNITA_SCANLINE(line);
    SAPPHIRE_GPU2D_HBLANK_TRACE_BEFORE_UNITB_SCANLINE(line);
    GPU2D_Renderer->DrawScanline(line, &GPU2D_B);
    SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_UNITB_SCANLINE(line);
}

if (line < 191)
{
    SAPPHIRE_GPU2D_HBLANK_TRACE_BEFORE_UNITA_SPRITES(line);
    GPU2D_Renderer->DrawSprites(line+1, &GPU2D_A);
    SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_UNITA_SPRITES(line);
    SAPPHIRE_GPU2D_HBLANK_TRACE_BEFORE_UNITB_SPRITES(line);
    GPU2D_Renderer->DrawSprites(line+1, &GPU2D_B);
    SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_UNITB_SPRITES(line);
    SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_UNITB_SPRITES_DIAG(line);
}

SAPPHIRE_GPU2D_HBLANK_TRACE_BEFORE_CHECK_DMAS(line);
NDS.CheckDMAs(0, 0x02);
SAPPHIRE_GPU2D_HBLANK_TRACE_AFTER_CHECK_DMAS(line);
"""


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_outputs(*, upstream_sequence: list[str], generated_inc: str) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_INC.write_text(generated_inc, encoding="utf-8")
    manifest = {
        "pinnedCoreCommit": PINNED_COMMIT,
        "normalizedSequence": NORMALIZED_SEQUENCE,
        "upstreamNormalizedSequence": upstream_sequence,
        "generatedIncSha256": sha256_text(generated_inc),
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def verify() -> int:
    upstream_path = lib_root() / "src" / "GPU.cpp"
    if not upstream_path.is_file():
        print(f"upstream GPU.cpp missing: {upstream_path}", file=sys.stderr)
        return 1

    upstream_sequence = normalize_block(extract_upstream_block(read_text(upstream_path)))
    if upstream_sequence != NORMALIZED_SEQUENCE:
        print("upstream normalized sequence mismatch", file=sys.stderr)
        print("expected:", NORMALIZED_SEQUENCE, file=sys.stderr)
        print("actual:", upstream_sequence, file=sys.stderr)
        return 1

    if not GENERATED_INC.is_file():
        print(f"missing generated include: {GENERATED_INC}", file=sys.stderr)
        return 1

    generated_sequence = normalize_block(read_text(GENERATED_INC))
    if generated_sequence != NORMALIZED_SEQUENCE:
        print("generated include normalized sequence mismatch", file=sys.stderr)
        print("expected:", NORMALIZED_SEQUENCE, file=sys.stderr)
        print("actual:", generated_sequence, file=sys.stderr)
        return 1

    print("[SapphireGpu2DEventBlock] verify ok")
    return 0


def generate() -> int:
    upstream_path = lib_root() / "src" / "GPU.cpp"
    upstream_sequence = normalize_block(extract_upstream_block(read_text(upstream_path)))
    generated_inc = build_generated_inc()
    write_outputs(upstream_sequence=upstream_sequence, generated_inc=generated_inc)
    print(f"[SapphireGpu2DEventBlock] wrote {GENERATED_INC}")
    return verify()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    if args.verify:
        return verify()
    return generate()


if __name__ == "__main__":
    raise SystemExit(main())
