#!/usr/bin/env python3
"""Vendor Sapphire FrameLatch dependency closure from pinned melonDS-android (S74)."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ANDROID_ROOT = Path(r"C:\Users\Admin\Documents\git\melonDS-android")
MANIFEST_PATH = REPO_ROOT / "tools" / "sapphire_frame_latch_vendor_manifest.json"
OUTPUT_DIR = REPO_ROOT / "src" / "frontend" / "qt_sdl" / "SapphireGenerated"
GENERATED_CPP = OUTPUT_DIR / "SapphireFrameLatchCore.cpp"
GENERATED_H = OUTPUT_DIR / "SapphireFrameLatchCore.h"
GENERATION_MANIFEST = OUTPUT_DIR / "GENERATION_MANIFEST.json"

CPP_PROLOGUE = """// Generated by tools/generate_sapphire_frame_latch.py — do not edit.
#include "SapphireFrameLatchCore.h"

#include <algorithm>
#include <chrono>
#include <cstring>
#include <sstream>
#include <vector>

#include "GPU.h"
#include "GPU3D_Vulkan.h"
#include "NDS.h"
#include "Platform.h"
#include "SapphireGPU2DSoftAccess.h"
#include "VulkanDesktopCompat.h"

using namespace melonDS;
using namespace melonDS::Platform;

namespace MelonDSAndroid
{
"""

CPP_EPILOGUE = """
} // namespace MelonDSAndroid
"""


def android_root() -> Path:
    env = os.environ.get("SAPPHIRE_ANDROID_ROOT")
    return Path(env) if env else DEFAULT_ANDROID_ROOT


def load_vendor_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines(keepends=True)


def extract_line_range(lines: list[str], start: int, end: int) -> str:
    return "".join(lines[start - 1 : end])


def extract_state_members(header_lines: list[str], start: int, end: int) -> str:
    body = extract_line_range(header_lines, start, end)
    return "\n".join("    " + line.rstrip() for line in body.splitlines())


def transform_upstream_body(text: str) -> str:
    text = text.replace("MelonInstance::", "SapphireFrameLatchCore::")
    text = re.sub(r"\bnds->", "nds_->", text)
    text = re.sub(r"\bnds ==", "nds_ ==", text)
    text = re.sub(r"\bnds !=", "nds_ !=", text)
    text = re.sub(
        r"dynamic_cast<const GPU2D::SoftRenderer\*>\(&nds_->GPU\.GetRenderer2D\(\)\)",
        "nds_->GPU.TryGetSapphireRenderer2D()",
        text,
    )
    text = re.sub(
        r"dynamic_cast<GPU2D::SoftRenderer\*>\(&nds_->GPU\.GetRenderer2D\(\)\)",
        "nds_->GPU.TryGetSapphireRenderer2D()",
        text,
    )
    text = re.sub(
        r"nds_->GPU\.Framebuffer\[([^\]]+)\]\[([^\]]+)\]\.get\(\)",
        r"nds_->GPU.Framebuffer[\1][\2]",
        text,
    )
    text = text.replace(
        "GPU2D::SoftRenderer::DebugCaptureStats",
        "melonDS::SapphireGPU2D::SoftRenderer::DebugCaptureStats",
    )
    if "MelonInstance::" in text:
        raise ValueError("unconverted MelonInstance:: token remains")
    if re.search(r"(?<![_A-Za-z0-9])nds(?!_)", text):
        raise ValueError("bare nds token remains after transform")
    return text


def build_header(state_members: str) -> str:
    return f"""// Generated by tools/generate_sapphire_frame_latch.py — do not edit.
#pragma once

#include <array>

#include "VulkanReference/FrameQueue.h"
#include "VulkanReference/VulkanOutput.h"

namespace melonDS {{
class NDS;
}}

namespace MelonDSAndroid
{{

class SapphireFrameLatchCore
{{
public:
    void bindNds(melonDS::NDS* nds) {{ nds_ = nds; }}

    void clearLatchedSoftPackedFrameSnapshot();
    bool updateVulkanTemporal3dHistoryGate();
    [[nodiscard]] bool isVulkanTemporal3dHistoryGateActive() const;
    bool latchSoftPackedFrameSnapshot(
        const Frame* frame,
        int frontBuffer,
        bool screenSwap,
        bool useStructuredVulkan2D);

    [[nodiscard]] const SoftPackedFrameSnapshot& lastSnapshot() const
    {{
        return lastSoftPackedFrameSnapshot;
    }}

    SoftPackedFrameSnapshot& mutableLastSnapshot()
    {{
        return lastSoftPackedFrameSnapshot;
    }}

    [[nodiscard]] const SoftPackedFrameSnapshot& previousSnapshot() const
    {{
        return previousSoftPackedFrameSnapshot;
    }}

    [[nodiscard]] int structuredCaptureGateFrames() const
    {{
        return vulkanStructuredCaptureGateFrames;
    }}

    [[nodiscard]] bool regularCaptureTransitionResyncPending() const
    {{
        return vulkanRegularCaptureTransitionResyncPending;
    }}

    void clearRegularCaptureTransitionResyncPending()
    {{
        vulkanRegularCaptureTransitionResyncPending = false;
    }}

    void forceTemporalHistoryGateOff() noexcept
    {{
        vulkanTemporal3dHistoryGateFrames = 0;
    }}

private:
    melonDS::NDS* nds_ = nullptr;
{state_members}
}};

}} // namespace MelonDSAndroid
"""


def build_core_cpp(vendor_manifest: dict, android_root_path: Path) -> str:
    cpp_path = android_root_path / vendor_manifest["upstreamRelativeCpp"]
    header_path = android_root_path / vendor_manifest["upstreamRelativeHeader"]
    cpp_lines = read_lines(cpp_path)
    header_lines = read_lines(header_path)

    chunks = [CPP_PROLOGUE]
    for region in vendor_manifest["cppRegions"]:
        raw = extract_line_range(cpp_lines, region["start"], region["end"])
        chunks.append(transform_upstream_body(raw))
        chunks.append("\n")
    chunks.append(CPP_EPILOGUE)
    return "".join(chunks)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_outputs(header_text: str, cpp_text: str, vendor_manifest: dict) -> dict:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_H.write_text(header_text, encoding="utf-8", newline="\n")
    GENERATED_CPP.write_text(cpp_text, encoding="utf-8", newline="\n")
    manifest = {
        "upstreamTag": vendor_manifest["upstreamTag"],
        "upstreamFrontendCommit": vendor_manifest["upstreamFrontendCommit"],
        "generatedHeaderSha256": sha256_bytes(header_text.encode("utf-8")),
        "generatedCoreSha256": sha256_bytes(cpp_text.encode("utf-8")),
        "cppRegions": vendor_manifest["cppRegions"],
        "headerStateMemberStart": vendor_manifest["headerStateMemberStart"],
        "headerStateMemberEnd": vendor_manifest["headerStateMemberEnd"],
    }
    GENERATION_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def verify_upstream_commit(vendor_manifest: dict, android_root_path: Path) -> None:
    expected = vendor_manifest["upstreamFrontendCommit"]
    proc = subprocess.run(
        ["git", "-C", str(android_root_path), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"failed to read upstream commit: {proc.stderr.strip()}")
    actual = proc.stdout.strip()
    if actual != expected:
        raise RuntimeError(
            f"upstream commit mismatch: expected {expected}, got {actual}"
        )


def compare_bytes(path_a: Path, path_b: Path) -> None:
    if path_a.read_bytes() != path_b.read_bytes():
        raise RuntimeError(f"byte mismatch: {path_a} != {path_b}")


def generate_to_directory(
    output_dir: Path,
    vendor_manifest: dict,
    android_root_path: Path,
) -> tuple[str, str]:
    header_path = android_root_path / vendor_manifest["upstreamRelativeHeader"]
    header_lines = read_lines(header_path)
    state_members = extract_state_members(
        header_lines,
        vendor_manifest["headerStateMemberStart"],
        vendor_manifest["headerStateMemberEnd"],
    )
    header_text = build_header(state_members)
    cpp_text = build_core_cpp(vendor_manifest, android_root_path)
    out_h = output_dir / "SapphireFrameLatchCore.h"
    out_cpp = output_dir / "SapphireFrameLatchCore.cpp"
    out_h.write_text(header_text, encoding="utf-8", newline="\n")
    out_cpp.write_text(cpp_text, encoding="utf-8", newline="\n")
    return header_text, cpp_text


def verify_read_only() -> int:
    vendor_manifest = load_vendor_manifest()
    android_root_path = android_root()
    verify_upstream_commit(vendor_manifest, android_root_path)

    with tempfile.TemporaryDirectory(prefix="sapphire-latch-verify-") as temp_name:
        temp_dir = Path(temp_name)
        header_text, cpp_text = generate_to_directory(
            temp_dir,
            vendor_manifest,
            android_root_path,
        )
        compare_bytes(temp_dir / "SapphireFrameLatchCore.h", GENERATED_H)
        compare_bytes(temp_dir / "SapphireFrameLatchCore.cpp", GENERATED_CPP)

    proc = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "diff", "--exit-code", "--", str(GENERATED_H), str(GENERATED_CPP)],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr, file=sys.stderr)
        raise RuntimeError("verify modified committed generated files")

    print("Sapphire FrameLatch vendor verify OK")
    print(f"generatedCoreSha256={sha256_bytes(cpp_text.encode('utf-8'))}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    if args.verify:
        try:
            return verify_read_only()
        except RuntimeError as exc:
            print(str(exc), file=sys.stderr)
            return 1

    vendor_manifest = load_vendor_manifest()
    android_root_path = android_root()
    verify_upstream_commit(vendor_manifest, android_root_path)
    header_path = android_root_path / vendor_manifest["upstreamRelativeHeader"]
    header_lines = read_lines(header_path)
    state_members = extract_state_members(
        header_lines,
        vendor_manifest["headerStateMemberStart"],
        vendor_manifest["headerStateMemberEnd"],
    )
    header_text = build_header(state_members)
    cpp_text = build_core_cpp(vendor_manifest, android_root_path)
    manifest = write_outputs(header_text, cpp_text, vendor_manifest)
    print(f"Wrote {OUTPUT_DIR}")
    print(f"generatedCoreSha256={manifest['generatedCoreSha256']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
