#!/usr/bin/env python3
"""Generate Sapphire FrameLatch core from pinned melonDS-android sources (S73-3)."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ANDROID_ROOT = Path(r"C:\Users\Admin\Documents\git\melonDS-android")
OUTPUT_DIR = REPO_ROOT / "src/frontend/qt_sdl/SapphireGenerated"
MANIFEST_PATH = OUTPUT_DIR / "GENERATION_MANIFEST.json"
UPSTREAM_TAG = "0.7.0.rc4"
UPSTREAM_RELATIVE = "app/src/main/cpp/MelonInstance.cpp"

EXTRACT_FUNCTIONS = (
    "packedPixelHasVisibleColor",
    "packedPixelIsOpaqueBlack",
    "packedControlMarksProtectedBlack2D",
    "softPackedFramesAlternate3dOwner",
    "softPackedFrameNeedsReusablePreviousFrame",
    "softPackedFrameUsesTemporal3dHistory",
    "clearLatchedSoftPackedFrameSnapshot",
    "updateVulkanTemporal3dHistoryGate",
    "latchSoftPackedFrameSnapshot",
)

HEADER_TEMPLATE = """// Generated by tools/generate_sapphire_frame_latch.py — do not edit.
#pragma once

#include "VulkanReference/FrameQueue.h"
#include "VulkanReference/VulkanOutput.h"

namespace melonDS { class NDS; }

namespace MelonDSAndroid
{

class SapphireFrameLatchCore
{
public:
    void bindNds(melonDS::NDS* nds) { nds_ = nds; }

    void clearLatchedSoftPackedFrameSnapshot();
    bool updateVulkanTemporal3dHistoryGate();
    bool latchSoftPackedFrameSnapshot(
        const Frame* frame,
        int frontBuffer,
        bool screenSwap,
        bool useStructuredVulkan2D);

private:
    melonDS::NDS* nds_ = nullptr;
};

} // namespace MelonDSAndroid
"""


def android_root() -> Path:
    env = os.environ.get("SAPPHIRE_ANDROID_ROOT")
    if env:
        return Path(env)
    return DEFAULT_ANDROID_ROOT


def read_upstream() -> str:
    path = android_root() / UPSTREAM_RELATIVE
    if not path.is_file():
        raise FileNotFoundError(f"upstream source missing: {path}")
    return path.read_text(encoding="utf-8")


def find_function_block(source: str, name: str) -> str | None:
    patterns = (
        rf"\bMelonInstance::{re.escape(name)}\s*\(",
        rf"\bbool\s+{re.escape(name)}\s*\(",
        rf"\bvoid\s+{re.escape(name)}\s*\(",
        rf"\bu32\s+{re.escape(name)}\s*\(",
        rf"\bint\s+{re.escape(name)}\s*\(",
    )
    match = None
    for pattern in patterns:
        match = re.search(pattern, source)
        if match:
            break
    if not match:
        return None
    start = match.start()
    brace = source.find("{", match.end())
    if brace == -1:
        return None
    depth = 0
    for index in range(brace, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return source[start : index + 1]
    return None


def normalize_for_parity(text: str) -> str:
    text = re.sub(r"\r\n", "\n", text)
    text = re.sub(r"//.*", "", text)
    text = re.sub(r"/\*[\s\S]*?\*/", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def apply_transforms(text: str) -> str:
    text = text.replace("MelonInstance::", "SapphireFrameLatchCore::")
    text = text.replace("nds->", "nds_->")
    return text


def build_core_cpp(upstream: str) -> str:
    chunks: list[str] = [
        "// Generated by tools/generate_sapphire_frame_latch.py — do not edit.",
        '#include "SapphireFrameLatchCore.h"',
        "",
        "#include \"GPU.h\"",
        "#include \"NDS.h\"",
        "#include \"Platform.h\"",
        "",
        "using namespace melonDS;",
        "",
        "namespace MelonDSAndroid",
        "{",
    ]
    for name in EXTRACT_FUNCTIONS:
        block = find_function_block(upstream, name)
        if block is None:
            chunks.append(f"// MISSING upstream function: {name}")
            continue
        chunks.append(apply_transforms(block))
        chunks.append("")
    chunks.append("} // namespace MelonDSAndroid")
    chunks.append("")
    return "\n".join(chunks)


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_outputs(core_cpp: str, upstream: str) -> dict:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    header_path = OUTPUT_DIR / "SapphireFrameLatchCore.h"
    cpp_path = OUTPUT_DIR / "SapphireFrameLatchCore.cpp"
    header_path.write_text(HEADER_TEMPLATE, encoding="utf-8", newline="\n")
    cpp_path.write_text(core_cpp, encoding="utf-8", newline="\n")
    manifest = {
        "upstreamTag": UPSTREAM_TAG,
        "upstreamRelativePath": UPSTREAM_RELATIVE,
        "extractedFunctions": list(EXTRACT_FUNCTIONS),
        "generatedHeaderSha256": sha256(HEADER_TEMPLATE),
        "generatedCoreSha256": sha256(core_cpp),
        "upstreamNormalizedSha256": sha256(
            normalize_for_parity(
                "\n".join(
                    block
                    for name in EXTRACT_FUNCTIONS
                    if (block := find_function_block(upstream, name)) is not None
                )
            )
        ),
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def verify() -> int:
    if not MANIFEST_PATH.is_file():
        print("generation manifest missing; run without --verify first", file=sys.stderr)
        return 1
    stored = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    upstream = read_upstream()
    core_cpp = build_core_cpp(upstream)
    manifest = write_outputs(core_cpp, upstream)
    if manifest["generatedCoreSha256"] != stored.get("generatedCoreSha256"):
        print("generated core drifted from committed manifest", file=sys.stderr)
        return 1
    print("Sapphire FrameLatch core generation verify OK")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    if args.verify:
        return verify()
    upstream = read_upstream()
    core_cpp = build_core_cpp(upstream)
    manifest = write_outputs(core_cpp, upstream)
    print(f"Wrote {OUTPUT_DIR}")
    print(f"generatedCoreSha256={manifest['generatedCoreSha256']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
