#!/usr/bin/env python3
"""Materialize and verify Sapphire vendor sources for MelonPrimeDS."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "tools" / "sapphire_vendor_manifest.json"
UPSTREAM_ROOT = REPO_ROOT / "src" / "SapphireVendor" / "upstream"

HEADER_GUARD_RE = re.compile(
    r"^#ifndef\s+\S+\s*\n#define\s+\S+\s*\n",
    re.MULTILINE,
)
HEADER_GUARD_END_RE = re.compile(r"^#endif\s//\s*\S+\s*\n?", re.MULTILINE)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def resolve_reference_root(entry: dict) -> Path | None:
    repo = entry["upstream_repository"]
    if repo.endswith("melonDS-android"):
        env = os.environ.get("SAPPHIRE_ANDROID_ROOT")
        return Path(env) if env else None
    if repo.endswith("melonDS-android-lib"):
        env = os.environ.get("SAPPHIRE_ANDROID_LIB_ROOT")
        return Path(env) if env else None
    return None


def snapshot_path(entry: dict) -> Path:
    repo_key = "melonDS-android" if entry["upstream_repository"].endswith("melonDS-android") else "melonDS-android-lib"
    return UPSTREAM_ROOT / repo_key / entry["upstream_path"]


def materialize_upstream(manifest: dict) -> list[str]:
    errors: list[str] = []
    for entry in manifest.get("vendor_files", []):
        ref_root = resolve_reference_root(entry)
        if ref_root is None:
            errors.append(f"{entry['local_path']}: missing Sapphire clone env")
            continue
        source = ref_root / entry["upstream_path"]
        target = snapshot_path(entry)
        if not source.is_file():
            errors.append(f"missing upstream source: {source}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(source.read_bytes())
        upstream_hash = sha256_file(source)
        if upstream_hash != entry["upstream_sha256"]:
            errors.append(
                f"{entry['upstream_path']}: upstream hash drift "
                f"(manifest {entry['upstream_sha256']}, got {upstream_hash})"
            )
    return errors


def verify_upstream_snapshots(manifest: dict) -> list[str]:
    errors: list[str] = []
    for entry in manifest.get("vendor_files", []):
        target = snapshot_path(entry)
        if not target.is_file():
            errors.append(f"missing upstream snapshot: {target.relative_to(REPO_ROOT)}")
            continue
        snapshot_hash = sha256_file(target)
        if snapshot_hash != entry["upstream_sha256"]:
            errors.append(
                f"{target.relative_to(REPO_ROOT)}: snapshot hash drift "
                f"(manifest {entry['upstream_sha256']}, got {snapshot_hash})"
            )
    return errors


def apply_desktop_vulkan_adapter(entry: dict, text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    repo = entry["upstream_repository"]
    ref = entry["upstream_commit_or_tag"]
    header = (
        f"// Source: {entry['upstream_repository']}\n"
        f"// {entry['upstream_path']} @ {ref}\n"
        f"// Generated by tools/vendor_sapphire.py; desktop adapter blocks are preserved locally.\n\n"
    )

    if entry["local_path"].endswith(".h"):
        text = HEADER_GUARD_RE.sub("", text, count=1)
        text = HEADER_GUARD_END_RE.sub("", text, count=1)
        if not text.startswith("#pragma once"):
            text = "#pragma once\n\n" + text.lstrip("\n")

    replacements = [
        ('#include "VulkanDispatch.h"', '#include <volk.h>'),
        ('#include "OpenGLContext.h"', '#include <volk.h>'),
        ('#include <EGL/egl.h>\n', ""),
        ('#include <EGL/eglext.h>\n', ""),
        ('#include <GLES3/gl3.h>\n', ""),
        ('#include "VulkanSurfacePresenterFragmentShaderData.h"',
         '#include <sapphire/VulkanSurfacePresenterFragmentShaderData.h>'),
        ('#include "VulkanSurfacePresenterVertexShaderData.h"',
         '#include <sapphire/VulkanSurfacePresenterVertexShaderData.h>'),
        ('namespace melonDS\n{', 'namespace melonDS::SapphireGPU2DCore::GPU2D\n{'),
        ('#include "GPU2D_Soft.h"', '#include "SapphireGPU2DCore/GPU2D_Soft.h"'),
        ('#include "GPU2D.h"', '#include "GPU2D.h"'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)

    if not text.startswith("// Source:"):
        text = header + text
    return text


def generate_local(entry: dict) -> str:
    source = snapshot_path(entry)
    if not source.is_file():
        raise FileNotFoundError(f"missing upstream snapshot: {source}")
    text = source.read_text(encoding="utf-8")
    mode = entry.get("parity_mode", "local_baseline")
    if mode == "exact_upstream":
        return text
    if entry.get("allowed_transform") == "desktop_vulkan_adapter":
        return apply_desktop_vulkan_adapter(entry, text)
    return text


def verify_generated(manifest: dict) -> list[str]:
    errors: list[str] = []
    for entry in manifest.get("vendor_files", []):
        local_path = REPO_ROOT / entry["local_path"]
        if not local_path.is_file():
            errors.append(f"missing local file: {entry['local_path']}")
            continue
        try:
            generated = generate_local(entry)
        except FileNotFoundError as exc:
            errors.append(str(exc))
            continue

        mode = entry.get("parity_mode", "local_baseline")
        if mode == "exact_upstream":
            if sha256_file(local_path) != sha256_file(snapshot_path(entry)):
                errors.append(
                    f"{entry['local_path']}: exact generated output mismatch with upstream snapshot"
                )
            continue

        if mode == "normalized_upstream":
            from check_sapphire_vendor_parity import normalize_vendor_text, sha256_bytes

            local_norm = normalize_vendor_text(local_path.read_text(encoding="utf-8"))
            generated_norm = normalize_vendor_text(generated)
            if local_norm != generated_norm:
                errors.append(
                    f"{entry['local_path']}: generated normalized output mismatch "
                    f"(local {sha256_bytes(local_norm.encode('utf-8'))}, "
                    f"generated {sha256_bytes(generated_norm.encode('utf-8'))})"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--materialize-upstream",
        action="store_true",
        help="Copy pinned upstream files into src/SapphireVendor/upstream",
    )
    parser.add_argument(
        "--verify-upstream-snapshots",
        action="store_true",
        help="Verify committed upstream snapshots match manifest hashes",
    )
    parser.add_argument(
        "--verify-generated",
        action="store_true",
        help="Verify committed local vendor files match generator output",
    )
    args = parser.parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))

    if not any(
        [args.materialize_upstream, args.verify_upstream_snapshots, args.verify_generated]
    ):
        parser.error("specify at least one action")

    errors: list[str] = []
    if args.materialize_upstream:
        errors.extend(materialize_upstream(manifest))
    if args.verify_upstream_snapshots:
        errors.extend(verify_upstream_snapshots(manifest))
    if args.verify_generated:
        errors.extend(verify_generated(manifest))

    if errors:
        print("Sapphire vendor generation check FAILED:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print("Sapphire vendor generation check OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
