// Generated by tools/generate_sapphire_frame_queue.py — do not edit.
#pragma once

#include <array>
#include <chrono>
#include <condition_variable>
#include <deque>
#include <mutex>
#include <optional>
#include <queue>

#include "VulkanReference/FrameQueue.h"

namespace MelonDSAndroid
{

class SapphireFrameQueueCore
{
    friend class DesktopFrameLifetimeTracker;
    friend class ::FrameQueue;

public:
    SapphireFrameQueueCore();

    Frame* getRenderFrame(const FrameQueuePolicy& policy);
    Frame* getPresentFrame(
        const FrameQueuePolicy& policy,
        std::optional<std::chrono::time_point<std::chrono::steady_clock>> deadline);
    Frame* getPresentCandidate(
        const FrameQueuePolicy& policy,
        std::optional<std::chrono::time_point<std::chrono::steady_clock>> deadline);
    Frame* getReusablePreviousFrame(const FrameQueuePolicy& policy);
    void recycleRenderFrame(Frame* frame);
    void commitPresentedFrame(Frame* frame, const FrameQueuePolicy& policy);
    void deferPresentedFrame(Frame* frame, const FrameQueuePolicy& policy);
    void pushRenderedFrame(Frame* frame, const FrameQueuePolicy& policy);
    void discardRenderedFrame(Frame* frame);
    void requestPresentationResync();
    void requestFastForwardPresentationTransition();
    FrameQueueStats takeStatsSnapshotAndReset();
    void rebuildFreeQueueFromStates();
    void sanitizeFreeQueueLocked();
    void resetQueueContainers();

    [[nodiscard]] std::array<Frame, FRAME_QUEUE_SIZE>& frames() { return frames_; }
    [[nodiscard]] const std::array<Frame, FRAME_QUEUE_SIZE>& frames() const { return frames_; }

private:
    enum class PresentDropCause : u8
    {
        Stale = 0,
        StealForRender = 1,
        Deadline = 2,
        BacklogTrim = 3,
    };

    static FrameQueuePolicy sanitizePolicy(FrameQueuePolicy policy);
    void rebuildFreeQueueLocked();
    void dropPendingFramesToBacklogLocked(u64 maxBacklogDepth, bool treatAsFastForwardSkip);
    void updateBacklogStatsLocked();
    void recordPresentedFrameAgeLocked(Frame* frame, u64 nowNs);
    void recordDroppedFrameLocked(Frame* frame, PresentDropCause cause, u64 nowNs);

        std::mutex frameLock;
        std::condition_variable presentFrameReadyCondition;
        std::array<Frame, FRAME_QUEUE_SIZE> frames_{};
        std::queue<Frame*> freeQueue{};
        std::deque<Frame*> presentQueue{};
        Frame* previousFrame = nullptr;
        Frame* pendingPresentFrame = nullptr;
        bool suppressPreviousFrameReuse = false;
        u64 nextFrameId = 1;
        FrameQueueStats stats{};
};

} // namespace MelonDSAndroid
