// Generated by tools/generate_sapphire_frame_latch.py — do not edit.
#pragma once

#include <array>

#include "VulkanReference/FrameQueue.h"
#include "VulkanReference/VulkanOutput.h"

namespace melonDS {
class NDS;
}

namespace MelonDSAndroid
{

class SapphireFrameLatchCore
{
public:
    void bindNds(melonDS::NDS* nds) { nds_ = nds; }

    void clearLatchedSoftPackedFrameSnapshot();
    bool updateVulkanTemporal3dHistoryGate();
    [[nodiscard]] bool isVulkanTemporal3dHistoryGateActive() const;
    bool latchSoftPackedFrameSnapshot(
        const Frame* frame,
        int frontBuffer,
        bool screenSwap,
        bool useStructuredVulkan2D);

    [[nodiscard]] const SoftPackedFrameSnapshot& lastSnapshot() const
    {
        return lastSoftPackedFrameSnapshot;
    }

    SoftPackedFrameSnapshot& mutableLastSnapshot()
    {
        return lastSoftPackedFrameSnapshot;
    }

    [[nodiscard]] const SoftPackedFrameSnapshot& previousSnapshot() const
    {
        return previousSoftPackedFrameSnapshot;
    }

    [[nodiscard]] int structuredCaptureGateFrames() const
    {
        return vulkanStructuredCaptureGateFrames;
    }

    [[nodiscard]] bool regularCaptureTransitionResyncPending() const
    {
        return vulkanRegularCaptureTransitionResyncPending;
    }

    void clearRegularCaptureTransitionResyncPending()
    {
        vulkanRegularCaptureTransitionResyncPending = false;
    }

    void forceTemporalHistoryGateOff() noexcept
    {
        vulkanTemporal3dHistoryGateFrames = 0;
    }

private:
    melonDS::NDS* nds_ = nullptr;
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> lastValidTopScreenCapture3dDsFrame{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> lastValidBottomScreenCapture3dDsFrame{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> lastValidTopScreenResolvedPrimary{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> lastValidBottomScreenResolvedPrimary{};
        std::array<u8, SoftPackedFrameSnapshot::kLineCount> lastValidTopScreenResolvedPrimaryLines{};
        std::array<u8, SoftPackedFrameSnapshot::kLineCount> lastValidBottomScreenResolvedPrimaryLines{};
        bool hasLastValidTopScreenCapture3dDsFrame = false;
        bool hasLastValidBottomScreenCapture3dDsFrame = false;
        bool vulkanRegularCaptureTransitionResyncPending = false;
        int vulkanStructuredCaptureGateFrames = 0;
        int vulkanTemporal3dHistoryGateFrames = 0;
        int vulkanTemporal3dNotReadyFrames = 0;
        int vulkanTemporal3dHistoryDebugLogsRemaining = 0;
        bool lastVulkanFastForwardPresentationState = false;
        int vulkanFastForwardPreviousFrameFallbackFrames = 0;
        SoftPackedFrameSnapshot lastSoftPackedFrameSnapshot;
        SoftPackedFrameSnapshot previousSoftPackedFrameSnapshot;
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineATopPlane0{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineATopPlane1{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineATopControl{};
        std::array<u32, SoftPackedFrameSnapshot::kLineCount> cachedEngineATopLineMeta{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineABottomPlane0{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineABottomPlane1{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedEngineABottomControl{};
        std::array<u32, SoftPackedFrameSnapshot::kLineCount> cachedEngineABottomLineMeta{};
        bool cachedEngineATopValid = false;
        bool cachedEngineABottomValid = false;
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedAtypicalDisplayTopPrimary{};
        std::array<u32, SoftPackedFrameSnapshot::kPixelCount> cachedAtypicalDisplayBottomPrimary{};
        std::array<u8, SoftPackedFrameSnapshot::kLineCount> cachedAtypicalDisplayTopPrimaryLines{};
        std::array<u8, SoftPackedFrameSnapshot::kLineCount> cachedAtypicalDisplayBottomPrimaryLines{};
        int framesSinceLastScreenSwapToggle = 1024;
        bool wasInAlternatingMode = false;
};

} // namespace MelonDSAndroid
