// Generated by tools/generate_sapphire_frame_latch.py — do not edit.
#pragma once

#include "VulkanReference/FrameQueue.h"
#include "VulkanReference/VulkanOutput.h"

namespace melonDS { class NDS; }

namespace MelonDSAndroid
{

class SapphireFrameLatchCore
{
public:
    void bindNds(melonDS::NDS* nds) { nds_ = nds; }

    void clearLatchedSoftPackedFrameSnapshot();
    bool updateVulkanTemporal3dHistoryGate();
    bool latchSoftPackedFrameSnapshot(
        const Frame* frame,
        int frontBuffer,
        bool screenSwap,
        bool useStructuredVulkan2D);

private:
    melonDS::NDS* nds_ = nullptr;
};

} // namespace MelonDSAndroid
