name: macOS
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci/vcpkg-update
  pull_request:
    branches:
      - master
env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"
  CMAKE_VERSION: "3.28.3"
jobs:
  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: ${{ matrix.arch }}
    runs-on: macos-14
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
        
      - name: Install dependencies for package building
        run: |
          brew install autoconf automake autoconf-archive libtool python-setuptools
        
      # 特定バージョンのCMakeをインストール（最小限の変更）
      - name: Install specific CMake version
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-macos-universal.tar.gz
          tar -xzf cmake-${{ env.CMAKE_VERSION }}-macos-universal.tar.gz
          echo "${{ github.workspace }}/cmake-${{ env.CMAKE_VERSION }}-macos-universal/CMake.app/Contents/bin" >> $GITHUB_PATH
        
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c
          
      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: release-mac-${{ matrix.arch }}
          buildPreset: release-mac-${{ matrix.arch }}
          configurePresetAdditionalArgs: "['-DMELONDS_EMBED_BUILD_INFO=ON']"
          
      - name: Compress app bundle
        shell: bash
        run: |
          cd build/release-mac-${{ matrix.arch }}
          zip -r -y ../../macOS-${{ matrix.arch }}.zip melonDS.app
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-${{ matrix.arch }}
          path: macOS-${{ matrix.arch }}.zip
          retention-days: 1
  universal-binary:
    name: Universal binary
    needs: [build-macos]
    runs-on: macos-13
    continue-on-error: true
    steps:
      - name: Download x86_64
        uses: actions/download-artifact@v4
        with:
          name: macOS-x86_64
          path: x86_64
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: macOS-arm64
          path: arm64
      - name: Combine app bundles
        shell: bash
        run: |
          unzip x86_64/*.zip -d x86_64
          unzip arm64/*.zip -d arm64
          lipo {x86_64,arm64}/melonDS.app/Contents/MacOS/melonDS -create -output melonDS
          cp -a arm64/melonDS.app melonDS.app
          cp melonDS melonDS.app/Contents/MacOS/melonDS
          codesign -s - --deep melonDS.app
          zip -r -y macOS-universal.zip melonDS.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-universal
          path: macOS-universal.zip
