name: macOS
on:
  workflow_dispatch:
jobs:
  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: ${{ matrix.arch }}
    runs-on: macos-14
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Install dependencies for package building
        run: |
          brew install autoconf automake autoconf-archive libtool python-setuptools
      - name: Set up CMake
        uses: lukka/get-cmake@latest
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 53bef8994c541b6561884a8395ea35715ece75db
      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: release-mac-${{ matrix.arch }}
          buildPreset: release-mac-${{ matrix.arch }}
          configurePresetAdditionalArgs: "['-DMELONDS_EMBED_BUILD_INFO=ON']"
      - name: Compress app bundle
        shell: bash
        run: |
          cd build/release-mac-${{ matrix.arch }}
          mv melonDS.app melonPrimeDS.app
          mv melonPrimeDS.app/Contents/MacOS/melonDS melonPrimeDS.app/Contents/MacOS/melonPrimeDS
          zip -r -y ../../melonprimeDS-macOS-${{ matrix.arch }}.zip melonPrimeDS.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: melonprimeDS-macOS-${{ matrix.arch }}
          path: melonprimeDS-macOS-${{ matrix.arch }}.zip
  universal-binary:
    name: Universal binary
    needs: [build-macos]
    runs-on: macos-13
    continue-on-error: true
    steps:
      - name: Download x86_64
        uses: actions/download-artifact@v4
        with:
          name: melonprimeDS-macOS-x86_64
          path: x86_64
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: melonprimeDS-macOS-arm64
          path: arm64
      - name: Combine app bundles
        shell: bash
        run: |
          unzip x86_64/*.zip -d x86_64
          unzip arm64/*.zip -d arm64
          lipo {x86_64,arm64}/melonPrimeDS.app/Contents/MacOS/melonPrimeDS -create -output melonPrimeDS
          cp -a arm64/melonPrimeDS.app melonPrimeDS.app
          cp melonPrimeDS melonPrimeDS.app/Contents/MacOS/melonPrimeDS
          codesign -s - --deep melonPrimeDS.app
          zip -r -y melonprimeDS-macOS-universal.zip melonPrimeDS.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: melonprimeDS-macOS-universal
          path: melonprimeDS-macOS-universal.zip
#     - name: Clean up architecture-specific artifacts
#       uses: geekyeggo/delete-artifact@v4
#       with:
#         failOnError: false
#         name: |
#           melonprimeDS-macOS-x86_64
#           melonprimeDS-macOS-arm64