name: Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions

  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_DISABLE_METRICS: 1
  VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_binary_cache,readwrite

jobs:
  build:
    runs-on: windows-2025

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: false
          path-type: inherit
          pacboy: >-
            gcc:p
            cmake:p
            ninja:p
            make:p
            pkgconf:p

      - name: Ensure cache directories exist
        run: |
          mkdir -p "${{ github.workspace }}/vcpkg_binary_cache"
          mkdir -p "${{ github.workspace }}/vcpkg_installed"

      - name: Cache vcpkg downloads, installed, and binaries
        id: vcpkg_cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/vcpkg/downloads
            ${{ github.workspace }}/vcpkg_installed
            ${{ github.workspace }}/vcpkg_binary_cache
          key: ${{ runner.os }}-vcpkg-ucrt64-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json', 'cmake/overlay-triplets/**', 'cmake/overlay-ports/**') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-ucrt64-

      - name: Setup vcpkg
        run: |
          if [ ! -d "$VCPKG_ROOT/.git" ]; then
            echo "Cloning vcpkg..."
            git clone --depth 1 https://github.com/Microsoft/vcpkg.git "$VCPKG_ROOT"
          fi

          if [ ! -f "$VCPKG_ROOT/vcpkg.exe" ]; then
            echo "Bootstrapping vcpkg..."
            "$VCPKG_ROOT/bootstrap-vcpkg.bat" -disableMetrics
          fi

          "$VCPKG_ROOT/vcpkg.exe" version

      - name: Configure
        run: |
          cmake --preset=release-mingw-x86_64 \
            -DMELONDS_EMBED_BUILD_INFO=ON \
            -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_INSTALLED_DIR="${{ github.workspace }}/vcpkg_installed"

      - name: Build
        run: |
          cmake --build --preset=release-mingw-x86_64 --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: melonDS-windows-x86_64
          path: ./build/release-mingw-x86_64/melonDS.exe